# coturn-turbo: Mode 2 - Turbo + io_uring
listening-port=3478
listening-ip=0.0.0.0
relay-ip=172.17.123.27
external-ip=122.51.14.87/172.17.123.27
realm=mycoturn
lt-cred-mech
user=test:test123
turbo
turbo-backend=io_uring
turbo-l1-warmup enable
turbo-api-port=8080
verbose
simple-log
