# Standard coturn config (no Turbo) - for testing Build 1
listening-port=3478
listening-ip=0.0.0.0
relay-ip=172.17.123.27
external-ip=122.51.14.87/172.17.123.27
realm=mycoturn
lt-cred-mech
user=test:test123
verbose
simple-log
log-file=/home/web/local/var/log/turnserver/turbo.log
